# Distributed under the MIT License.
# See LICENSE.txt for details.

# Build the documentation and check for problems, then upload as a workflow
# artifact and deploy to gh-pages.
name: Documentation

on: workflow_call

jobs:
  doc_check:
    name: Documentation
    runs-on: ubuntu-latest
    container:
      image: ${{ inputs.container || 'sxscollaboration/spectre:dev' }}
      env:
        CCACHE_DIR: /work/ccache
        CCACHE_READONLY: 1
        CCACHE_COMPILERCHECK: content
        CCACHE_BASEDIR: $GITHUB_WORKSPACE
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      # Work around https://github.com/actions/checkout/issues/760
      - name: Trust checkout
        run: |
          git config --global --add safe.directory $GITHUB_WORKSPACE
      # These can be installed directly in the Docker container instead
      - name: Install Python dependencies
        run: |
          python3 -m pip install -r support/Python/dev_requirements.txt
      - name: Download release notes
        uses: actions/download-artifact@v8
        id: release-notes
        with:
          name: release-notes
          path: /work
      - name: Append release notes to changelog
        # The sed command escapes @ symbols at beginning of words (GitHub
        # usernames) so they aren't interpreted as Doxygen commands
        run: |
          echo "" >> docs/Changelog.md
          cat /work/release_notes.md | sed 's/\(\B\@\)/\\\1/g' \
            >> docs/Changelog.md
      - name: Restore ccache
        uses: actions/cache/restore@v5
        id: restore-ccache
        env:
          CACHE_KEY_PREFIX: ccache-gcc-11-Debug-pch-ON
        with:
          path: /work/ccache
          key: "${{ env.CACHE_KEY_PREFIX }}-${{ github.run_id }}"
          restore-keys: |
            ${{ env.CACHE_KEY_PREFIX }}-
      # - Make sure to use the same build configuration as the unit tests from
      #   which we restore the ccache.
      # - Set `BUILD_TESTING=OFF` to test a CMake configuration with tests
      #   turned off.
      - name: Configure with cmake
        run: >
          mkdir build && cd build

          cmake
          -D CMAKE_C_COMPILER=gcc-11
          -D CMAKE_CXX_COMPILER=g++-11
          -D CMAKE_Fortran_COMPILER=gfortran-11
          -D CMAKE_CXX_FLAGS="-Werror"
          -D OVERRIDE_ARCH=x86-64
          -D CHARM_ROOT=${CHARM_ROOT}
          -D CMAKE_BUILD_TYPE=Debug
          -D SPECTRE_DEBUG_Og=ON
          -D DEBUG_SYMBOLS=OFF
          -D USE_PCH=ON
          -D USE_XSIMD=ON
          -D USE_CCACHE=ON
          -D ENABLE_OPENMP=ON
          -D BUILD_PYTHON_BINDINGS=ON
          -D BUILD_SHARED_LIBS=ON
          -D MEMORY_ALLOCATOR=SYSTEM
          -D BUILD_DOCS=ON
          -D BUILD_TESTING=OFF
          -D SPECTRE_AUTODIFF=ON
          -D SPECTRE_FETCH_MISSING_DEPS=ON
          $GITHUB_WORKSPACE
      - name: Check documentation
        working-directory: build
        run: |
          make doc-check
      # Re-build with coverage information on pushes to develop for deployment
      # to gh-pages.
      - name: Build documentation with coverage
        if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
        working-directory: build
        run: |
          make doc-coverage
      - name: Build Python docs
        working-directory: build
        run: |
          make py-docs -j4
      # Upload as an artifact to make available to deployment and to PRs
      - name: Prepare for upload
        working-directory: build
        run: |
          tar -cf docs-html.tar --directory docs/html .
      - name: Upload documentation
        uses: actions/upload-artifact@v7
        with:
          name: docs-html
          path: build/docs-html.tar
