# Distributed under the MIT License.
# See LICENSE.txt for details.

# Continuous integration tests that pull requests are required to pass. This
# workflow can also be dispatched manually to tag and release versions.
name: Tests

# Set any defaults for the runs below.
# - use bash as the default shell since this is almost certainly what
#   is always expected. We use regular expressions in a few places
#   that rely on bash.
defaults:
  run:
    shell: bash

# Note that by default the jobs only run on the base repository, testing pull
# requests and merge commits. Enable GitHub Actions in your fork's repository
# settings to also run the tests on every push to one of your branches.
on:
  # We run all jobs when pull requests are opened, commits are pushed, or pull
  # requests are re-opened after being closed.
  # The jobs triggered by this event run on the base repository of the pull
  # request, so they have access to its caches.
  pull_request:
  # We run those jobs that require no information about a pull request (e.g.
  # unit tests) also on `push` events. This setup tests merge commits into
  # `develop` and also builds up caches on `develop` that can be re-used by PRs.
  # It also runs the jobs on forks if they have GitHub Actions enabled.
  push:
    branches-ignore:
      - gh-pages
  # Allow running the workflow manually to run tests and optionally release a
  # version on success (see the dev guide on "Automatic versioning")
  workflow_dispatch:
    inputs:
      release_version:
        description: >
          Enter a version name YYYY.MM.DD[.TWEAK] to create a release on success
        required: false
        default: ''
      timezone:
        description: >
          Timezone used for validating the version name. The release must be
          approved by the end of the day in the specified timezone. See
          /usr/share/zoneinfo for a list of possible values.
        required: false
        default: 'America/Los_Angeles'
      clear_ccache:
        description: >
          Enter 'yes' without quotes to clear ccache before running
        required: false
        default: ''
      container:
        description: >
          Container to use for builds
        required: false
        default: 'sxscollaboration/spectre:dev'
  # Allow running this workflow as a job in another workflow. This is used to
  # test a new Docker container before publishing it.
  workflow_call:
    inputs:
      container:
        description: >
          Container to use for builds
        required: false
        type: string
        default: 'sxscollaboration/spectre:dev'

# Cancel all other queued or in-progress runs of this workflow when it is
# scheduled, so repeated pushes to a branch or a PR don't block CI. Repeated
# pushes to 'develop' and 'release' are not canceled, so every merge commit is
# tested.
concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/develop'
    && github.ref != 'refs/heads/release' }}

jobs:
  check_commits:
    uses: $/.github/workflows/CheckCommits.yaml
  check_files_and_formatting:
    uses: $/.github/workflows/CheckFilesAndFormatting.yaml
  clang_tidy:
    uses: $/.github/workflows/ClangTidy.yaml
  doc_check:
    uses: $/.github/workflows/DocCheck.yaml
    needs: check_files_and_formatting
  docs-deploy:
    uses: $/.github/workflows/DocsDeploy.yaml
    needs: doc_check
  unit_tests:
    uses: $/.github/workflows/UnitTests.yaml
  unit_tests_macos:
    uses: $/.github/workflows/UnitTestsMacOs.yaml
  release_version:
    uses: $/.github/workflows/ReleaseVersion.yaml
    needs:
      - check_files_and_formatting
      - doc_check
      - unit_tests
  arch_datastructures_tests:
    uses: $/.github/workflows/ArchDataStructuresTests.yaml





